[package]
name = "sputnik-staking"
version = "1.0.0"
authors = ["Sputnik Devs <near-daos@protonmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { git = "https://github.com/ctindogaru/near-sdk-rs", branch = "allow_deserialization" }
near-contract-standards = { git = "https://github.com/ctindogaru/near-sdk-rs", branch = "allow_deserialization" }
hex = "0.4.2"

[dev-dependencies]
near-sdk-sim = { git = "https://github.com/ctindogaru/near-sdk-rs", branch = "allow_deserialization" }
test-token = { path = "../test-token" }
