[package]
name = "sputnikdao2"
version = "2.0.0"
authors = ["Sputnik Devs <near-daos@protonmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { git = "https://github.com/ctindogaru/near-sdk-rs", branch = "add_is_account_registered", features = ["unstable"]}
near-contract-standards = { git = "https://github.com/ctindogaru/near-sdk-rs", branch = "add_is_account_registered" }
hex = "0.4.2"

[dependencies.serde_with]
version = "1.4.0"

[dev-dependencies]
near-sdk-sim = { git = "https://github.com/ctindogaru/near-sdk-rs", branch = "add_is_account_registered" }
test-token = { path = "../test-token" }
sputnik-staking = { path = "../sputnik-staking" }